return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "ast-grep",
        "basedpyright",
        "csharpier",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "fantomas",
        "fsautocomplete",
        "gofumpt",
        "goimports",
        "golangci-lint",
        "gopls",
        "hadolint",
        "json-lsp",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "netcoredbg",
        "omnisharp",
        "pyright",
        "ruff",
        "shfmt",
        "sonarlint-language-server",
        "stylua",
        "taplo",
      },
    },
  },
}
